appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: r+dLHNzdO7+9sV4hF8jht2W1O1OcWV6rVmRx/TCDkkFnCmQZWHfQ5XuPQl+024+/7hEz5oyWq47XfbCKOfwd22i8QUSZRDTPxcQbm7wJ28IbpcfDxcYc0+1dy1HVWENVxTwmZ960O8PePjYrCJMcjCD14YXLBN/fCkbYEzLH3hfGkmFkgDz5ZIZoIzz8ts6LsiwWdBqvvF53mvnzW8wUtALXSuQeKTeC4OFG8+9MYbs9sGwd2XXGPABvAU3gagqt1ZITPZmVSQbmxIsdD+ZamQ/odGUhh1ww2gnVKVzqz5K2jXmVHWo+TcS1qD1uileKlUClGL5FvTH0kWADCl/4KqQPFaP25GHeD/p+30fozY767bta4a5pf6S66JPqPiHM9Sn/GJktGEhZ0EtjvmS6HHFZaE/Vl5VRZ3xjagGkTUmpZDpv8Z66pI3BanoXUwjMPHgy/0vwsN4mljB4ckJKUI0cpVdIJc8yJ9NAumnKw/9RYygnaXMHbDkSBP1E7a5D4mmc7lLNSkdvr7dsACPx8BTlVaDe9ebyfmxPUKDZWtR3ABCBWsdEyCJ3tYQEcULJ3z4hVFQb4QeKTpY4llE8hAafMlu/crYI1j1VB0v3u6KzdT7b2UZSwPsE6HJlfEMvZSZquL9lBRU96E5X04aEoItPijmx0InmSkNifdpxkR8=}
bot:
  automerge: true
