travis:
  secure:
    BINSTAR_TOKEN: pOngFTHnMLhMiLY4yx4BqjlWtU4i537qC2BRyh3glN0gunmBplueAPFSzbH/7VElGfCVWjvMZI5OZpmk3Iw++mG+qe9hXUw5/t6m62arFtO0Jjw24+8ZcDeGLltwJVSQ98evV/EGLAprDbDSQpdHggl10no7ic2Auy9YByxmyAC8Ir2yIZ2I0Oy71Cf0QjpeRf5SkIE4HA/FIGDNcxfcyjOjay7jeTdjeqTa/x6rm5f6uuyYuOcKS3EKJEYey/R1ckCgH2NY6qRXGSvyIJQCciHWrVTp4rr1hYhzNvMQIDz+Xo90voCMe3pDnm9fYiFhuYNP3l+p4cuRUSvsWj/kOIBm+dxNblQAB5hSpZkIhcTnh1xqltLB9uo4/Lh+5jM4xMxLyAnfaL2vIoIj59Tb6Jh0fMUl+au1wYDT775iuVu6GtcpKSqZOUbUP/0v9u/h95NbfroQ6RiJv4aPhRNe5fh30NWx02TKqxNfSR4NsHqQP+tCf8C3Upps6Ei9ckB8ThgPqEZodOnchcbdfhzccLfxwz/dPD05p8qCDvZzMHiRkpYrhzM/Sx1VXaBENyXylBcyMNeOzF9zOKCntprz7So9XaPT5Zpaz8rflJ9qOP7n/+oiqXErG4YYyHWQr/Dc7a6mVJclf7NcbLldyAYr/Tmc5xEuWiRoi0X2kQ87eOM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
