travis:
  secure:
    BINSTAR_TOKEN: k4VaaQX8zy7BzE5p1rstRnOt/mDhmmS+z8OckCTB6t/nrYyS6IhS15L86qjACDqOLsiENj8lA1fFga1fhqo8dweEjLmC3VhLkAxjbx3tQ2iB1eJ7Nz3ryapqOl4k6j9oxoDP5zdGkbtnfnlQWyX7xLZAV+TLqPWs//g53uQINUGAXuT6aLJNB8+kbCdR47Ql3QQJpexuOAWWCDUe8XeYlurWrxYiS2HaA546fd8J7vttUtbKbuYqjcaxfN9uDFLsCL8DBywYKyYolltdFoyR0q4VVgpIqiJrEW/49O42F89dfbu3C2jpZJPMjHrYZ8iMAkALZDDSFC7znM2cE1Tg31Q9bSGzyiGMZRhU5tQiL9pmiwpgSsmrgd9qOaILrc1pYwlnmvV01p753Iss8AxxcRmeQ+KCkdXr9aO787ZkPiZA6uaJgRXVXuZr1wx6Ag6l68NDMt5KHVZbKZCsuxmJzGuenf7Vvtb5SqJaJsS7Uq0oXtUrQmFYKmEjz5OX+EihxmWGbdLu7puSge/9rraH6oWd5LTp/WIH+Butusr1gaWC4OFfZjD54+Ra0CS3XDDaG/y6TVP2WGR1GISIa2OWhnqKNf8EAmRmkwosmQqGykVTwQeNlL6f0NyT3sMBBh8hLj3v6rkJGNUZmKRoS4RNaDVB/FFkv/h2NqHl9W+iRiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
